# Change these first
owner: sewanee-raval # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Main Sewanee Site
    url: https://new.sewanee.edu
  - name: Library Website
    url: https://library.sewanee.edu
  - name: School of Letters Website
    url: https://letters.sewanee.edu/
  - name: School of Theology Website
    url: https://theology.sewanee.edu/
  - name: University Registrar Website
    url: https://registrar.sewanee.edu/
assignees:
  - Sewanee-raval
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Sewanee Main Websites"
  introMessage: This is an external status page for Sewanee Websites
  navbar:
    - title: Status
      href: /upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
